#!/usr/bin/env python3
"""
Parses Il2CppDumper output and generates offsets.h for ESP build.
Run automatically by GitHub Actions workflow.
"""

import re
import json
import argparse
from pathlib import Path

def parse_dump_cs(dump_path: str) -> dict:
    """Extract key class/method/field offsets from dump.cs"""
    
    targets = {
        'Camera': {
            'class': r'class Camera\s*:\s*Behaviour',
            'worldToCameraMatrix': r'worldToCameraMatrix',
            'cameraToWorldMatrix': r'cameraToWorldMatrix',
            'main': r'public static Camera main'
        },
        'Transform': {
            'class': r'class Transform\s*:\s*Component',
            'position': r'public Vector3 position',
            'forward': r'public Vector3 forward'
        },
        'Player': {
            # CoD Mobile specific — adjust based on actual dump
            'class': r'class PlayerController|class CG_Pawn',
            'health': r'public (?:float|int) (?:health|m_health|Health)',
            'team': r'public (?:int|TeamType) (?:team|m_team|Team)',
            'name': r'public string (?:name|m_name|PlayerName)'
        }
    }
    
    offsets = {}
    content = Path(dump_path).read_text(errors='ignore')
    
    # Extract using regex on dump.cs format:
    # // RVA: 0x1234567 Offset: 0x1234567 VA: 0x1234567
    def find_offset(pattern, content):
        match = re.search(pattern + r'.*?\n.*?Offset:\s*(0x[0-9a-fA-F]+)', content)
        return match.group(1) if match else None
    
    for class_name, patterns in targets.items():
        offsets[class_name] = {}
        for key, pattern in patterns.items():
            if key == 'class':
                continue
            off = find_offset(pattern, content)
            if off:
                offsets[class_name][key] = off
    
    return offsets

def parse_script_json(script_path: str) -> dict:
    """Extract raw addresses from script.json for pointer chains"""
    with open(script_path) as f:
        data = json.load(f)
    
    # Find GameManager / PlayerList pointers
    pointers = {}
    for item in data:
        name = item.get('Name', '')
        if 'GameManager' in name or 'PlayerManager' in name:
            pointers[name] = item.get('Address', 0)
    
    return pointers

def generate_header(offsets: dict, pointers: dict, version: str) -> str:
    """Generate C++ header with all offsets"""
    
    header = f"""// Auto-generated by extract_offsets.py
// CoD Mobile version: {version}
// Generated: {__import__('datetime').datetime.now().isoformat()}
// DO NOT EDIT MANUALLY — regenerate via workflow

#pragma once
#include <cstdint>

namespace offsets {{
    
    // IL2CPP binary base (resolved at runtime via dlopen)
    inline uintptr_t libil2cpp_base = 0;
    
    // Camera system
    namespace Camera {{
        inline constexpr uintptr_t main_static = {offsets.get('Camera', {}).get('main', '0x0')};
        inline constexpr uintptr_t worldToCameraMatrix = {offsets.get('Camera', {}).get('worldToCameraMatrix', '0x0')};
        inline constexpr uintptr_t cameraToWorldMatrix = {offsets.get('Camera', {}).get('cameraToWorldMatrix', '0x0')};
    }}
    
    // Transform component
    namespace Transform {{
        inline constexpr uintptr_t position = {offsets.get('Transform', {}).get('position', '0x0')};
        inline constexpr uintptr_t forward = {offsets.get('Transform', {}).get('forward', '0x0')};
    }}
    
    // Player entity
    namespace Player {{
        inline constexpr uintptr_t health = {offsets.get('Player', {}).get('health', '0x0')};
        inline constexpr uintptr_t team = {offsets.get('Player', {}).get('team', '0x0')};
        inline constexpr uintptr_t name = {offsets.get('Player', {}).get('name', '0x0')};
    }}
    
    // Static pointers (from script.json)
"""
    
    for name, addr in pointers.items():
        safe_name = re.sub(r'[^a-zA-Z0-9]', '_', name)
        header += f"    inline constexpr uintptr_t {safe_name} = {addr};\n"
    
    header += "}\n"
    return header

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dump', required=True, help='Path to dump.cs')
    parser.add_argument('--script', required=True, help='Path to script.json')
    parser.add_argument('--out', required=True, help='Output header path')
    parser.add_argument('--version', default='unknown')
    args = parser.parse_args()
    
    offsets = parse_dump_cs(args.dump)
    pointers = parse_script_json(args.script)
    
    header = generate_header(offsets, pointers, args.version)
    Path(args.out).write_text(header)
    print(f"Generated {args.out} with {len(offsets)} classes, {len(pointers)} pointers")
